/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tennis;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFrame;
import model.MonMariaDbDataSource;

/**
 *
 * @author p1806052
 */
public class Fenetre extends javax.swing.JFrame {
    
    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlanningModifier = new javax.swing.JPanel();
        pLblPlanning3 = new javax.swing.JLabel();
        labelChoixP1 = new javax.swing.JLabel();
        comboChoixP1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        supprimerP1 = new javax.swing.JButton();
        tfAnneeDP1 = new javax.swing.JTextField();
        moisDP1 = new javax.swing.JTextField();
        jourDP1 = new javax.swing.JTextField();
        tfAnneeFP1 = new javax.swing.JTextField();
        moisFP1 = new javax.swing.JTextField();
        jourFP1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        panelPlanningHome = new javax.swing.JPanel();
        pLblPlanning = new javax.swing.JLabel();
        pCreerB = new javax.swing.JButton();
        pModifierP = new javax.swing.JButton();
        pSupprimerB = new javax.swing.JButton();
        panelPlanningCreer = new javax.swing.JPanel();
        labelNomP = new javax.swing.JLabel();
        labelDateDP = new javax.swing.JLabel();
        labelDateFP = new javax.swing.JLabel();
        tfNomP = new javax.swing.JTextField();
        tfAnneeDP = new javax.swing.JTextField();
        tfAnneeFP = new javax.swing.JTextField();
        moisDP = new javax.swing.JTextField();
        jourDP = new javax.swing.JTextField();
        moisFP = new javax.swing.JTextField();
        jourFP = new javax.swing.JTextField();
        creerPB = new javax.swing.JButton();
        pLblPlanning2 = new javax.swing.JLabel();
        panelPlanningSupprimer = new javax.swing.JPanel();
        pLblPlanning1 = new javax.swing.JLabel();
        comboChoixP = new javax.swing.JComboBox<>();
        labelChoixP = new javax.swing.JLabel();
        supprimerP = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        panelPlanningModifier.setMaximumSize(new java.awt.Dimension(800, 400));
        panelPlanningModifier.setMinimumSize(new java.awt.Dimension(800, 400));
        panelPlanningModifier.setPreferredSize(new java.awt.Dimension(800, 400));

        pLblPlanning3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pLblPlanning3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pLblPlanning3.setText("Modifier Planning");
        pLblPlanning3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelChoixP1.setText("Choissisez un planning: ");

        comboChoixP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboChoixP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboChoixP1ActionPerformed(evt);
            }
        });

        jLabel3.setText("date de début: ");

        jLabel4.setText("date de fin: ");

        supprimerP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supprimerP1.setText("Modifier");
        supprimerP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerP1ActionPerformed(evt);
            }
        });

        tfAnneeDP1.setText("yyyy");
        tfAnneeDP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnneeDP1ActionPerformed(evt);
            }
        });

        moisDP1.setText("mm");

        jourDP1.setText("dd");

        tfAnneeFP1.setText("yyyy");

        moisFP1.setText("mm");

        jourFP1.setText("dd");

        jTextField3.setEditable(false);
        jTextField3.setText("dateDébutInitiale");

        jTextField4.setEditable(false);
        jTextField4.setText("dateFinInitiale");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        panelPlanningModifier.setVisible(false);

        javax.swing.GroupLayout panelPlanningModifierLayout = new javax.swing.GroupLayout(panelPlanningModifier);
        panelPlanningModifier.setLayout(panelPlanningModifierLayout);
        panelPlanningModifierLayout.setHorizontalGroup(
            panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                        .addComponent(labelChoixP1)
                        .addGap(18, 18, 18)
                        .addComponent(comboChoixP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlanningModifierLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                        .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                                    .addComponent(jourDP1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11))
                                .addComponent(moisDP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfAnneeDP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel4))
                            .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAnneeFP1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moisFP1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jourFP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addComponent(supprimerP1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                        .addComponent(pLblPlanning3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelPlanningModifierLayout.setVerticalGroup(
            panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pLblPlanning3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlanningModifierLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboChoixP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelChoixP1)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAnneeDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAnneeFP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moisFP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moisDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jourFP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jourDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlanningModifierLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(supprimerP1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setName("applicaationFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(800, 400));

        panelPlanningHome.setMaximumSize(new java.awt.Dimension(800, 400));
        panelPlanningHome.setMinimumSize(new java.awt.Dimension(800, 400));
        panelPlanningHome.setPreferredSize(new java.awt.Dimension(800, 400));

        pLblPlanning.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pLblPlanning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pLblPlanning.setText("Planning");
        pLblPlanning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pCreerB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pCreerB.setText("Créer");
        pCreerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCreerBActionPerformed(evt);
            }
        });

        pModifierP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pModifierP.setText("Modifier");
        pModifierP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pModifierPActionPerformed(evt);
            }
        });

        pSupprimerB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pSupprimerB.setText("Supprimer");
        pSupprimerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pSupprimerBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPlanningHomeLayout = new javax.swing.GroupLayout(panelPlanningHome);
        panelPlanningHome.setLayout(panelPlanningHomeLayout);
        panelPlanningHomeLayout.setHorizontalGroup(
            panelPlanningHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningHomeLayout.createSequentialGroup()
                .addGroup(panelPlanningHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlanningHomeLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(pLblPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPlanningHomeLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(pCreerB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(pModifierP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(pSupprimerB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        panelPlanningHomeLayout.setVerticalGroup(
            panelPlanningHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningHomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pLblPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(panelPlanningHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCreerB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pModifierP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSupprimerB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pLblPlanning.getAccessibleContext().setAccessibleName("pPlanningL");
        pCreerB.getAccessibleContext().setAccessibleName("pCreerB");
        pModifierP.getAccessibleContext().setAccessibleName("plModifierB");
        pSupprimerB.getAccessibleContext().setAccessibleName("pSupprimerB");

        panelPlanningCreer.setMaximumSize(new java.awt.Dimension(800, 400));
        panelPlanningCreer.setMinimumSize(new java.awt.Dimension(800, 400));

        labelNomP.setText("Nom Planning:");

        labelDateDP.setText("Date Début:");

        labelDateFP.setText("Date fIn:");

        tfNomP.setText("nom planning");
        tfNomP.setName(""); // NOI18N
        tfNomP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomPActionPerformed(evt);
            }
        });

        tfAnneeDP.setText("yyyy");

        tfAnneeFP.setText("yyyy");

        moisDP.setText("mm");

        jourDP.setText("dd");

        moisFP.setText("mm");

        jourFP.setText("dd");

        creerPB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        creerPB.setText("Créer");
        creerPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerPBActionPerformed(evt);
            }
        });

        pLblPlanning2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pLblPlanning2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pLblPlanning2.setText("Créer Planning");
        pLblPlanning2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPlanningCreerLayout = new javax.swing.GroupLayout(panelPlanningCreer);
        panelPlanningCreer.setLayout(panelPlanningCreerLayout);
        panelPlanningCreerLayout.setHorizontalGroup(
            panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningCreerLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomP)
                    .addComponent(labelDateDP)
                    .addComponent(labelDateFP))
                .addGap(104, 104, 104)
                .addGroup(panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlanningCreerLayout.createSequentialGroup()
                        .addComponent(tfAnneeFP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moisFP, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jourFP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPlanningCreerLayout.createSequentialGroup()
                        .addComponent(tfNomP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPlanningCreerLayout.createSequentialGroup()
                        .addComponent(tfAnneeDP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moisDP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jourDP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(creerPB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPlanningCreerLayout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(pLblPlanning2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        panelPlanningCreerLayout.setVerticalGroup(
            panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningCreerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pLblPlanning2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomP)
                    .addComponent(tfNomP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creerPB, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnneeDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moisDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jourDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDateDP))
                .addGap(23, 23, 23)
                .addGroup(panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDateFP)
                    .addComponent(tfAnneeFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moisFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jourFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        panelPlanningCreer.setVisible(false);

        panelPlanningSupprimer.setMaximumSize(new java.awt.Dimension(800, 400));
        panelPlanningSupprimer.setMinimumSize(new java.awt.Dimension(800, 400));
        panelPlanningSupprimer.setPreferredSize(new java.awt.Dimension(800, 400));

        pLblPlanning1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pLblPlanning1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pLblPlanning1.setText("Supprimer Planning");
        pLblPlanning1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboChoixP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboChoixP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboChoixPActionPerformed(evt);
            }
        });

        labelChoixP.setText("Choissisez un planning: ");

        supprimerP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supprimerP.setText("Supprimer");
        supprimerP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerPActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("dateDebutP");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("dateFinP");

        jLabel1.setText("date de début: ");

        jLabel2.setText("date de fin: ");

        panelPlanningSupprimer.setVisible(false);

        javax.swing.GroupLayout panelPlanningSupprimerLayout = new javax.swing.GroupLayout(panelPlanningSupprimer);
        panelPlanningSupprimer.setLayout(panelPlanningSupprimerLayout);
        panelPlanningSupprimerLayout.setHorizontalGroup(
            panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningSupprimerLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(labelChoixP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboChoixP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPlanningSupprimerLayout.createSequentialGroup()
                        .addComponent(pLblPlanning1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(panelPlanningSupprimerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addComponent(supprimerP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelPlanningSupprimerLayout.setVerticalGroup(
            panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningSupprimerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pLblPlanning1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlanningSupprimerLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(supprimerP, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPlanningSupprimerLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboChoixP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelChoixP)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlanningCreer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlanningCreer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPlanningHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelPlanningHome.getAccessibleContext().setAccessibleName("planningHomePanel");

        getAccessibleContext().setAccessibleName("applicationFrame");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pCreerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCreerBActionPerformed
        this.getContentPane().setVisible(false);
        this.setContentPane(panelPlanningCreer);
        panelPlanningCreer.setVisible(true);
    }//GEN-LAST:event_pCreerBActionPerformed

    private void tfNomPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomPActionPerformed

    private void creerPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creerPBActionPerformed

    private void pModifierPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pModifierPActionPerformed
        this.getContentPane().setVisible(false);
        this.setContentPane(panelPlanningModifier);
        panelPlanningModifier.setVisible(true);
    }//GEN-LAST:event_pModifierPActionPerformed

    private void pSupprimerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pSupprimerBActionPerformed
        this.getContentPane().setVisible(false);
        this.setContentPane(panelPlanningSupprimer);
        panelPlanningSupprimer.setVisible(true);
    }//GEN-LAST:event_pSupprimerBActionPerformed

    private void supprimerPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerPActionPerformed

    private void comboChoixPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboChoixPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboChoixPActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void comboChoixP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboChoixP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboChoixP1ActionPerformed

    private void supprimerP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerP1ActionPerformed

    private void tfAnneeDP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnneeDP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnneeDP1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        MonMariaDbDataSource dataSource;
        Connection connexionBD;
        
        try {
        dataSource = MonMariaDbDataSource.getMdbDataSource();
        connexionBD = dataSource.getConnection();
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboChoixP;
    private javax.swing.JComboBox<String> comboChoixP1;
    private javax.swing.JButton creerPB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jourDP;
    private javax.swing.JTextField jourDP1;
    private javax.swing.JTextField jourFP;
    private javax.swing.JTextField jourFP1;
    private javax.swing.JLabel labelChoixP;
    private javax.swing.JLabel labelChoixP1;
    private javax.swing.JLabel labelDateDP;
    private javax.swing.JLabel labelDateFP;
    private javax.swing.JLabel labelNomP;
    private javax.swing.JTextField moisDP;
    private javax.swing.JTextField moisDP1;
    private javax.swing.JTextField moisFP;
    private javax.swing.JTextField moisFP1;
    private javax.swing.JButton pCreerB;
    private javax.swing.JLabel pLblPlanning;
    private javax.swing.JLabel pLblPlanning1;
    private javax.swing.JLabel pLblPlanning2;
    private javax.swing.JLabel pLblPlanning3;
    private javax.swing.JButton pModifierP;
    private javax.swing.JButton pSupprimerB;
    private javax.swing.JPanel panelPlanningCreer;
    private javax.swing.JPanel panelPlanningHome;
    private javax.swing.JPanel panelPlanningModifier;
    private javax.swing.JPanel panelPlanningSupprimer;
    private javax.swing.JButton supprimerP;
    private javax.swing.JButton supprimerP1;
    private javax.swing.JTextField tfAnneeDP;
    private javax.swing.JTextField tfAnneeDP1;
    private javax.swing.JTextField tfAnneeFP;
    private javax.swing.JTextField tfAnneeFP1;
    private javax.swing.JTextField tfNomP;
    // End of variables declaration//GEN-END:variables
}
