/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tennis;

import java.sql.Connection;
import java.sql.SQLException;
import model.MonMariaDbDataSource;

/**
 *
 * @author p1806052
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlanningHome = new javax.swing.JPanel();
        pLblPlanning = new javax.swing.JLabel();
        pCreerB = new javax.swing.JButton();
        pModifierP = new javax.swing.JButton();
        pSupprimerB = new javax.swing.JButton();
        panelPlanningCreer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelPlanningModifier = new javax.swing.JPanel();
        panelPlanningSupprimer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("applicaationFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 400));

        pLblPlanning.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pLblPlanning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pLblPlanning.setText("Planning");
        pLblPlanning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pCreerB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pCreerB.setText("Créer");
        pCreerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCreerBActionPerformed(evt);
            }
        });

        pModifierP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pModifierP.setText("Modifier");

        pSupprimerB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pSupprimerB.setText("Supprimer");

        javax.swing.GroupLayout panelPlanningHomeLayout = new javax.swing.GroupLayout(panelPlanningHome);
        panelPlanningHome.setLayout(panelPlanningHomeLayout);
        panelPlanningHomeLayout.setHorizontalGroup(
            panelPlanningHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningHomeLayout.createSequentialGroup()
                .addGroup(panelPlanningHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlanningHomeLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(pLblPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPlanningHomeLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(pCreerB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(pModifierP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(pSupprimerB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panelPlanningHomeLayout.setVerticalGroup(
            panelPlanningHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningHomeLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(pLblPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelPlanningHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCreerB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pModifierP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSupprimerB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pLblPlanning.getAccessibleContext().setAccessibleName("pPlanningL");
        pCreerB.getAccessibleContext().setAccessibleName("pCreerB");
        pModifierP.getAccessibleContext().setAccessibleName("plModifierB");
        pSupprimerB.getAccessibleContext().setAccessibleName("pSupprimerB");

        jLabel1.setText("Nom Planning:");

        jLabel2.setText("Date Début:");

        jLabel3.setText("Date fIn:");

        panelPlanningCreer.setVisible(false);

        javax.swing.GroupLayout panelPlanningCreerLayout = new javax.swing.GroupLayout(panelPlanningCreer);
        panelPlanningCreer.setLayout(panelPlanningCreerLayout);
        panelPlanningCreerLayout.setHorizontalGroup(
            panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningCreerLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(587, Short.MAX_VALUE))
        );
        panelPlanningCreerLayout.setVerticalGroup(
            panelPlanningCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanningCreerLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        panelPlanningModifier.setVisible(false);

        javax.swing.GroupLayout panelPlanningModifierLayout = new javax.swing.GroupLayout(panelPlanningModifier);
        panelPlanningModifier.setLayout(panelPlanningModifierLayout);
        panelPlanningModifierLayout.setHorizontalGroup(
            panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        panelPlanningModifierLayout.setVerticalGroup(
            panelPlanningModifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelPlanningSupprimer.setVisible(false);

        javax.swing.GroupLayout panelPlanningSupprimerLayout = new javax.swing.GroupLayout(panelPlanningSupprimer);
        panelPlanningSupprimer.setLayout(panelPlanningSupprimerLayout);
        panelPlanningSupprimerLayout.setHorizontalGroup(
            panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        panelPlanningSupprimerLayout.setVerticalGroup(
            panelPlanningSupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningCreer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPlanningHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningCreer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPlanningSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelPlanningHome.getAccessibleContext().setAccessibleName("planningHomePanel");

        getAccessibleContext().setAccessibleName("applicationFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pCreerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCreerBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pCreerBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        MonMariaDbDataSource dataSource;
        Connection connexionBD;
        
        try {
        dataSource = MonMariaDbDataSource.getMdbDataSource();
        connexionBD = dataSource.getConnection();
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton pCreerB;
    private javax.swing.JLabel pLblPlanning;
    private javax.swing.JButton pModifierP;
    private javax.swing.JButton pSupprimerB;
    private javax.swing.JPanel panelPlanningCreer;
    private javax.swing.JPanel panelPlanningHome;
    private javax.swing.JPanel panelPlanningModifier;
    private javax.swing.JPanel panelPlanningSupprimer;
    // End of variables declaration//GEN-END:variables
}
